# Generated by Django 4.2.29 on 2026-03-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_sticker',
            field=models.CharField(blank=True, help_text='Emoji avatar sticker', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, help_text='Custom display name', max_length=100, null=True),
        ),
    ]
