# Generated by Django 4.2.29 on 2026-03-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_avatar_sticker_user_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, default='Hey there! I am using DME', max_length=255),
        ),
    ]
