# Generated by Django 4.2.29 on 2026-03-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(blank=True, help_text='Last time user disconnected from WebSocket', null=True),
        ),
    ]
