# Generated by Django 6.0.3 on 2026-04-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_fcmdevice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, default='Hey there! I am using DME', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='is_profile_complete',
            field=models.BooleanField(default=False, help_text='Whether the user has completed onboarding'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_username_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, help_text='Public profile name (can include emojis)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Unique username for search', max_length=150, unique=True),
        ),
    ]
