# Generated by Django 6.0.3 on 2026-05-14 17:06

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='profile_pics/'),
        ),
    ]
