# Generated by Django 6.0.3 on 2026-05-19 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('profile_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_views_received', to=settings.AUTH_USER_MODEL)),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_views_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile Interaction',
                'verbose_name_plural': 'Profile Interactions',
                'ordering': ['-viewed_at'],
                'unique_together': {('viewer', 'profile_owner')},
            },
        ),
    ]
