# Generated by Django 6.0.3 on 2026-06-13 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profileinteraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quick_reaction',
            field=models.CharField(default='❤️', help_text='Default emoji for double-tap reaction', max_length=10),
        ),
    ]
