# Generated by Django 6.0.3 on 2026-06-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_quick_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_seen_privacy',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('nobody', 'Nobody')], default='everyone', help_text='Last seen privacy setting', max_length=10),
        ),
    ]
