# Generated by Django 6.0.3 on 2026-07-10 14:22

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_last_seen_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=accounts.models.get_user_profile_storage, upload_to='profile_pics/'),
        ),
    ]
