/**
 * stickerPacks.ts
 * Curated sticker packs using real public Google Noto Emoji Animated Lottie JSON URLs.
 * 
 * Total: 7 packs with 28 stickers each = 196 premium animated stickers.
 */

export interface Sticker {
  id: string;
  name: string;
  url: string; // Direct Lottie JSON URL
}

export interface StickerPack {
  id: string;
  name: string;
  emoji: string; // Tab icon emoji
  stickers: Sticker[];
}

export const BUILT_IN_STICKER_PACKS: StickerPack[] = [
  {
    id: 'hearts',
    name: 'Hearts & Love',
    emoji: '❤️',
    stickers: [
      { id: 'redheart', name: 'Heart ❤️', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/2764_fe0f/lottie.json' },
      { id: 'sparklingheart', name: 'Sparkling Heart 💖', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f496/lottie.json' },
      { id: 'growingheart', name: 'Growing Heart 💗', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f497/lottie.json' },
      { id: 'beatingheart', name: 'Beating Heart 💓', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f493/lottie.json' },
      { id: 'twohearts', name: 'Two Hearts 💕', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f495/lottie.json' },
      { id: 'revolvinghearts', name: 'Revolving Hearts 💞', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f49e/lottie.json' },
      { id: 'brokenheart', name: 'Broken Heart 💔', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f494/lottie.json' },
      { id: 'orangeheart', name: 'Orange Heart 🧡', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f9e1/lottie.json' },
      { id: 'yellowheart', name: 'Yellow Heart 💛', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f499/lottie.json' },
      { id: 'greenheart', name: 'Green Heart 💚', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f49a/lottie.json' },
      { id: 'purpleheart', name: 'Purple Heart 💜', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f49c/lottie.json' },
      { id: 'whiteheart', name: 'White Heart 🤍', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f90d/lottie.json' },
      { id: 'heartwithribbon', name: 'Gift Heart 💝', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f49d/lottie.json' },
      { id: 'hearthands', name: 'Love 🫶', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1faf6/lottie.json' },
      { id: 'blackheart', name: 'Black Heart 🖤', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f5a4/lottie.json' },
      { id: 'brownheart', name: 'Brown Heart 🤎', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f90e/lottie.json' },
      { id: 'heartexclamation', name: 'Heart Exclamation ❣', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/2763_fe0f/lottie.json' },
      { id: 'kissingheart', name: 'Kissing Heart 😘', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f618/lottie.json' },
      { id: 'hearteyes', name: 'Heart Eyes 😍', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f60d/lottie.json' },
      { id: 'lovehearts', name: 'Love Hearts 🥰', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f970/lottie.json' },
      { id: 'heartdecoration', name: 'Heart Decoration 💟', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f49f/lottie.json' },
      { id: 'heartarrow', name: 'Heart Arrow 💘', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f498/lottie.json' },
      { id: 'loveletter', name: 'Love Letter 💌', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f48c/lottie.json' },
      { id: 'cupid', name: 'Cupid 💘', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f498/lottie.json' },
      { id: 'heartpulse', name: 'Heart Pulse 💓', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f493/lottie.json' },
      { id: 'sweatheart', name: 'Sweet Heart 💖', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f496/lottie.json' },
      { id: 'flameheart', name: 'Heart Fire 🔥', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f525/lottie.json' },
      { id: 'sparklelove', name: 'Sparkle Love ✨', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/2728/lottie.json' },
    ],
  },
  {
    id: 'smileys',
    name: 'Smileys',
    emoji: '😀',
    stickers: [
      { id: 'grin', name: 'Grin 😀', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f600/lottie.json' },
      { id: 'joy', name: 'Joy 😂', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f602/lottie.json' },
      { id: 'rofl', name: 'ROFL 🤣', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f923/lottie.json' },
      { id: 'smile', name: 'Smile 😊', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f60a/lottie.json' },
      { id: 'lovehearts', name: 'Hearts 🥰', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f970/lottie.json' },
      { id: 'hearteyes', name: 'Adore 😍', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f60d/lottie.json' },
      { id: 'kiss', name: 'Kiss 😘', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f618/lottie.json' },
      { id: 'tonguewink', name: 'Wink 😜', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f61c/lottie.json' },
      { id: 'cool', name: 'Cool 😎', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f60e/lottie.json' },
      { id: 'party', name: 'Party 🥳', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f973/lottie.json' },
      { id: 'thinking', name: 'Think 🤔', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f914/lottie.json' },
      { id: 'shush', name: 'Shh 🤫', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f92b/lottie.json' },
      { id: 'explode', name: 'Boom 🤯', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f92f/lottie.json' },
      { id: 'scream', name: 'Shock 😱', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f631/lottie.json' },
      { id: 'loudlycry', name: 'Sob 😭', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f62d/lottie.json' },
      { id: 'pleading', name: 'Please 🥺', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f97a/lottie.json' },
      { id: 'angry', name: 'Angry 😡', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f621/lottie.json' },
      { id: 'sleepy', name: 'Zzz 😴', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f634/lottie.json' },
      { id: 'ghost', name: 'Ghost 👻', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f47b/lottie.json' },
      { id: 'poop', name: 'Poop 💩', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f4a9/lottie.json' },
      { id: 'clown', name: 'Clown 🤡', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f921/lottie.json' },
      { id: 'nerd', name: 'Nerd 🤓', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f913/lottie.json' },
      { id: 'woozy', name: 'Woozy 🥴', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f974/lottie.json' },
      { id: 'sweatgrin', name: 'Sweat Grin 😅', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f605/lottie.json' },
      { id: 'cursing', name: 'Cursing 🤬', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f92c/lottie.json' },
      { id: 'mask', name: 'Mask 😷', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f637/lottie.json' },
      { id: 'dizzy', name: 'Dizzy 😵', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f635/lottie.json' },
      { id: 'smirk', name: 'Smirk 😏', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f60f/lottie.json' },
    ],
  },
  {
    id: 'people',
    name: 'People & Gestures',
    emoji: '👋',
    stickers: [
      { id: 'wave', name: 'Hi 👋', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f44b/lottie.json' },
      { id: 'thumbsup', name: 'Like 👍', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f44d/lottie.json' },
      { id: 'thumbsdown', name: 'Dislike 👎', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f44e/lottie.json' },
      { id: 'clap', name: 'Clap 👏', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f44f/lottie.json' },
      { id: 'raisinghands', name: 'Yay 🙌', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f64c/lottie.json' },
      { id: 'pray', name: 'Pray 🙏', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f64f/lottie.json' },
      { id: 'handshake', name: 'Shake 🤝', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f91d/lottie.json' },
      { id: 'biceps', name: 'Flex 💪', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f4aa/lottie.json' },
      { id: 'hearthands', name: 'Love 🫶', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1faf6/lottie.json' },
      { id: 'ok', name: 'OK 👌', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f44c/lottie.json' },
      { id: 'peace', name: 'Peace ✌️', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/270c_fe0f/lottie.json' },
      { id: 'rock', name: 'Rock 🤟', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f91f/lottie.json' },
      { id: 'fist', name: 'Fist 👊', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f44a/lottie.json' },
      { id: 'selfie', name: 'Selfie 🤳', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f933/lottie.json' },
      { id: 'facepalm', name: 'Oops 🤦', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f926/lottie.json' },
      { id: 'shrug', name: 'Shrug 🤷', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f937/lottie.json' },
      { id: 'pointleft', name: 'Point Left 👈', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f448/lottie.json' },
      { id: 'pointright', name: 'Point Right 👉', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f449/lottie.json' },
      { id: 'pointup', name: 'Point Up 👆', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/261d_fe0f/lottie.json' },
      { id: 'pointdown', name: 'Point Down 👇', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f447/lottie.json' },
      { id: 'callme', name: 'Call Me 🤙', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f919/lottie.json' },
      { id: 'crossedfingers', name: 'Luck 🤞', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f91e/lottie.json' },
      { id: 'write', name: 'Write ✍️', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/270d_fe0f/lottie.json' },
      { id: 'nails', name: 'Nails 💅', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f485/lottie.json' },
      { id: 'eyes', name: 'Eyes 👀', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f440/lottie.json' },
      { id: 'ear', name: 'Ear 👂', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f442/lottie.json' },
      { id: 'brain', name: 'Brain 🧠', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f9e0/lottie.json' },
      { id: 'tooth', name: 'Tooth 🦷', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1fa77/lottie.json' },
    ],
  },
  {
    id: 'animals',
    name: 'Animals & Nature',
    emoji: '🐶',
    stickers: [
      { id: 'dog', name: 'Dog 🐶', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f436/lottie.json' },
      { id: 'cat', name: 'Cat 🐱', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f431/lottie.json' },
      { id: 'monkey', name: 'Monkey 🐵', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f435/lottie.json' },
      { id: 'lion', name: 'Lion 🦁', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f981/lottie.json' },
      { id: 'tiger', name: 'Tiger 🐯', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f42f/lottie.json' },
      { id: 'frog', name: 'Frog 🐸', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f438/lottie.json' },
      { id: 'unicorn', name: 'Unicorn 🦄', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f984/lottie.json' },
      { id: 'bee', name: 'Bee 🐝', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f41d/lottie.json' },
      { id: 'owl', name: 'Owl 🦉', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f989/lottie.json' },
      { id: 'octopus', name: 'Octopus 🐙', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f419/lottie.json' },
      { id: 'fire', name: 'Fire 🔥', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f525/lottie.json' },
      { id: 'sparkles', name: 'Sparkles ✨', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/2728/lottie.json' },
      { id: 'bear', name: 'Bear 🐻', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f43b/lottie.json' },
      { id: 'panda', name: 'Panda 🐼', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f43c/lottie.json' },
      { id: 'koala', name: 'Koala 🐨', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f428/lottie.json' },
      { id: 'bunny', name: 'Bunny 🐰', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f430/lottie.json' },
      { id: 'fox', name: 'Fox 🦊', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f98a/lottie.json' },
      { id: 'wolf', name: 'Wolf 🐺', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f43a/lottie.json' },
      { id: 'pig', name: 'Pig 🐷', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f437/lottie.json' },
      { id: 'cow', name: 'Cow 🐮', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f42e/lottie.json' },
      { id: 'chicken', name: 'Chicken 🐔', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f414/lottie.json' },
      { id: 'penguin', name: 'Penguin 🐧', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f427/lottie.json' },
      { id: 'duck', name: 'Duck 🦆', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f986/lottie.json' },
      { id: 'eagle', name: 'Eagle 🦅', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f985/lottie.json' },
      { id: 'butterfly', name: 'Butterfly 🦋', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f98b/lottie.json' },
      { id: 'flower', name: 'Flower 🌸', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f338/lottie.json' },
      { id: 'sunflower', name: 'Sunflower 🌻', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f33b/lottie.json' },
      { id: 'rainbow', name: 'Rainbow 🌈', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f308/lottie.json' },
    ],
  },
  {
    id: 'food',
    name: 'Food & Drink',
    emoji: '🍔',
    stickers: [
      { id: 'burger', name: 'Burger 🍔', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f354/lottie.json' },
      { id: 'pizza', name: 'Pizza 🍕', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f355/lottie.json' },
      { id: 'fries', name: 'Fries 🍟', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f35f/lottie.json' },
      { id: 'popcorn', name: 'Popcorn 🍿', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f37f/lottie.json' },
      { id: 'donut', name: 'Donut 🍩', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f369/lottie.json' },
      { id: 'cake', name: 'Cake 🍰', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f370/lottie.json' },
      { id: 'icecream', name: 'Ice Cream 🍦', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f366/lottie.json' },
      { id: 'coffee', name: 'Coffee ☕', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/2615/lottie.json' },
      { id: 'boba', name: 'Boba 🧋', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f9cb/lottie.json' },
      { id: 'beer', name: 'Beer 🍺', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f37a/lottie.json' },
      { id: 'taco', name: 'Taco 🌮', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f32e/lottie.json' },
      { id: 'burrito', name: 'Burrito 🌯', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f32f/lottie.json' },
      { id: 'hotdog', name: 'Hotdog 🌭', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f32d/lottie.json' },
      { id: 'ramen', name: 'Ramen 🍜', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f35c/lottie.json' },
      { id: 'sushi', name: 'Sushi 🍣', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f363/lottie.json' },
      { id: 'bento', name: 'Bento 🍱', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f371/lottie.json' },
      { id: 'cookie', name: 'Cookie 🍪', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f36a/lottie.json' },
      { id: 'candy', name: 'Candy 🍬', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f36c/lottie.json' },
      { id: 'chocolate', name: 'Chocolate 🍫', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f36b/lottie.json' },
      { id: 'apple', name: 'Apple 🍎', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f34e/lottie.json' },
      { id: 'banana', name: 'Banana 🍌', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f34c/lottie.json' },
      { id: 'strawberry', name: 'Strawberry 🍓', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f353/lottie.json' },
      { id: 'watermelon', name: 'Watermelon 🍉', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f349/lottie.json' },
      { id: 'avocado', name: 'Avocado 🥑', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f951/lottie.json' },
      { id: 'cocktail', name: 'Cocktail 🍸', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f378/lottie.json' },
      { id: 'wine', name: 'Wine 🍷', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f377/lottie.json' },
      { id: 'juice', name: 'Juice 🧃', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f9c3/lottie.json' },
      { id: 'tea', name: 'Tea 🍵', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f375/lottie.json' },
    ],
  },
  {
    id: 'activities',
    name: 'Activities & Sports',
    emoji: '⚽',
    stickers: [
      { id: 'soccer', name: 'Soccer ⚽', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/26bd/lottie.json' },
      { id: 'basketball', name: 'Basketball 🏀', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f3c0/lottie.json' },
      { id: 'gaming', name: 'Gaming 🎮', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f3ae/lottie.json' },
      { id: 'art', name: 'Art 🎨', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f3a8/lottie.json' },
      { id: 'mic', name: 'Mic 🎤', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f3a4/lottie.json' },
      { id: 'headphones', name: 'Music 🎧', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f3a7/lottie.json' },
      { id: 'trophy', name: 'Trophy 🏆', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f3c6/lottie.json' },
      { id: 'target', name: 'Target 🎯', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f3af/lottie.json' },
      { id: 'baseball', name: 'Baseball ⚾', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/26be/lottie.json' },
      { id: 'football', name: 'Football 🏈', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f3c8/lottie.json' },
      { id: 'tennis', name: 'Tennis 🎾', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f3be/lottie.json' },
      { id: 'volleyball', name: 'Volleyball 🏐', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f3d0/lottie.json' },
      { id: 'bowling', name: 'Bowling 🎳', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f3b3/lottie.json' },
      { id: 'pingpong', name: 'Ping Pong 🏓', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f3d2/lottie.json' },
      { id: 'running', name: 'Running 🏃', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f3c3/lottie.json' },
      { id: 'dancing', name: 'Dancing 💃', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f483/lottie.json' },
      { id: 'skateboarding', name: 'Skateboarding 🛹', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f6f9/lottie.json' },
      { id: 'swimming', name: 'Swimming 🏊', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f3ca/lottie.json' },
      { id: 'surfing', name: 'Surfing 🏄', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f3c4/lottie.json' },
      { id: 'guitar', name: 'Guitar 🎸', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f3b8/lottie.json' },
      { id: 'violin', name: 'Violin 🎻', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f3bb/lottie.json' },
      { id: 'drums', name: 'Drums 🥁', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f941/lottie.json' },
      { id: 'saxophone', name: 'Saxophone 🎷', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f3b7/lottie.json' },
      { id: 'ticket', name: 'Ticket 🎫', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f3ab/lottie.json' },
      { id: 'medal', name: 'Medal 🏅', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f3c5/lottie.json' },
      { id: 'crown', name: 'Crown 👑', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f451/lottie.json' },
      { id: 'firecrackers', name: 'Fireworks 🎆', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f386/lottie.json' },
      { id: 'magic', name: 'Magic 🪄', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1fa84/lottie.json' },
    ],
  },
  {
    id: 'objects',
    name: 'Objects & Symbols',
    emoji: '💡',
    stickers: [
      { id: 'bulb', name: 'Idea 💡', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f4a1/lottie.json' },
      { id: 'rocket', name: 'Rocket 🚀', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f680/lottie.json' },
      { id: 'balloon', name: 'Balloon 🎈', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f388/lottie.json' },
      { id: 'popper', name: 'Popper 🎉', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f389/lottie.json' },
      { id: 'gift', name: 'Present 🎁', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f381/lottie.json' },
      { id: 'gem', name: 'Gem 💎', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f48e/lottie.json' },
      { id: 'heart', name: 'Heart ❤️', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/2764_fe0f/lottie.json' },
      { id: 'hundred', name: '100 💯', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f4af/lottie.json' },
      { id: 'bell', name: 'Bell 🔔', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f514/lottie.json' },
      { id: 'mobile', name: 'Phone 📱', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f4f1/lottie.json' },
      { id: 'laptop', name: 'Laptop 💻', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f4bb/lottie.json' },
      { id: 'camera', name: 'Camera 📸', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f4f7/lottie.json' },
      { id: 'tv', name: 'TV 📺', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f4fa/lottie.json' },
      { id: 'key', name: 'Key 🔑', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f511/lottie.json' },
      { id: 'lock', name: 'Lock 🔒', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f512/lottie.json' },
      { id: 'money', name: 'Money 💸', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f4b8/lottie.json' },
      { id: 'dollar', name: 'Dollar 💵', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f4b2/lottie.json' },
      { id: 'creditcard', name: 'Card 💳', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f4b3/lottie.json' },
      { id: 'envelope', name: 'Mail ✉️', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/2709_fe0f/lottie.json' },
      { id: 'package', name: 'Package 📦', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f4e6/lottie.json' },
      { id: 'calendar', name: 'Calendar 📅', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f4c5/lottie.json' },
      { id: 'clock', name: 'Clock ⏰', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/23f0/lottie.json' },
      { id: 'compass', name: 'Compass 🧭', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f9ed/lottie.json' },
      { id: 'map', name: 'Map 🗺️', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f5fa_fe0f/lottie.json' },
      { id: 'shield', name: 'Shield 🛡️', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/1f6e1_fe0f/lottie.json' },
      { id: 'star', name: 'Star ⭐', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/2b50/lottie.json' },
      { id: 'checkmark', name: 'Check ✅', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/2705/lottie.json' },
      { id: 'warning', name: 'Warning ⚠️', url: 'https://fonts.gstatic.com/s/e/notoemoji/latest/26a0_fe0f/lottie.json' },
    ],
  },
];
