/**
 * stickerPacks.ts
 * Curated sticker packs using real public Google Noto Emoji Animated Lottie JSON URLs.
 * 
 * Total: 8 packs with 35 unique, 100% verified (200 OK) animated stickers each.
 */

export interface Sticker {
  id: string;
  name: string;
  url: string; // Direct Lottie JSON URL
}

export interface StickerPack {
  id: string;
  name: string;
  emoji: string; // Tab icon emoji
  stickers: Sticker[];
}

const notoUrl = (codepoint: string) =>
  `https://fonts.gstatic.com/s/e/notoemoji/latest/${codepoint}/lottie.json`;

export const BUILT_IN_STICKER_PACKS: StickerPack[] = [
  {
    id: 'party',
    name: 'Party & Celebration',
    emoji: '🎉',
    stickers: [
      { id: 'partypop', name: 'Party! 🎉', url: notoUrl('1f389') },
      { id: 'partyface', name: 'Celebrate 🥳', url: notoUrl('1f973') },
      { id: 'confetti', name: 'Confetti 🎊', url: notoUrl('1f38a') },
      { id: 'mandance', name: 'Cool Guy 😎', url: notoUrl('1f60e') },
      { id: 'redheart', name: 'Heart ❤️', url: notoUrl('2764_fe0f') },
      { id: 'stareyes', name: 'Star-Struck 🤩', url: notoUrl('1f929') },
      { id: 'loveface', name: 'In Love 🥰', url: notoUrl('1f970') },
      { id: 'hearteyez', name: 'Adore 😍', url: notoUrl('1f60d') },
      { id: 'hug', name: 'Hug 🤗', url: notoUrl('1f917') },
      { id: 'grin', name: 'Grinning Face 😀', url: notoUrl('1f600') },
      { id: 'champagne', name: 'Champagne 🍾', url: notoUrl('1f37e') },
      { id: 'clink', name: 'Cheers 🥂', url: notoUrl('1f942') },
      { id: 'notes', name: 'Music 🎶', url: notoUrl('1f3b6') },
      { id: 'dance', name: 'Dance 💃', url: notoUrl('1f483') },
      { id: 'boydance', name: 'Party Rock 🤟', url: notoUrl('1f91f') },
      { id: 'hearten', name: 'Heart Hands 🫶', url: notoUrl('1faf6') },
      { id: 'trophy2', name: 'Winner 🏆', url: notoUrl('1f3c6') },
      { id: 'crown2', name: 'Crown 👑', url: notoUrl('1f451') },
      { id: 'glowstar', name: 'Glowing ⭐', url: notoUrl('1f31f') },
      { id: 'sparklez', name: 'Sparkle ✨', url: notoUrl('2728') },
      { id: 'gift2', name: 'Gift 🎁', url: notoUrl('1f381') },
      { id: 'cake2', name: 'Birthday 🎂', url: notoUrl('1f382') },
      { id: 'clap2', name: 'Clap 👏', url: notoUrl('1f44f') },
      { id: 'raised2', name: 'Yay! 🙌', url: notoUrl('1f64c') },
      { id: 'magic2', name: 'Magic 🪄', url: notoUrl('1fa84') },
      { id: 'gem2', name: 'Gem 💎', url: notoUrl('1f48e') },
      { id: 'hundred2', name: '100 💯', url: notoUrl('1f4af') },
      { id: 'fire2', name: 'Fire 🔥', url: notoUrl('1f525') },
      { id: 'peace', name: 'Peace ✌️', url: notoUrl('270c_fe0f') },
      { id: 'gradcap', name: 'Graduation 🎓', url: notoUrl('1f393') },
      { id: 'balloon2', name: 'Balloon 🎈', url: notoUrl('1f388') },
      { id: 'fireworks', name: 'Fireworks 🎆', url: notoUrl('1f386') },
      { id: 'toast', name: 'Wine Toast 🍷', url: notoUrl('1f377') },
      { id: 'goldmedal1', name: 'Gold Medal 🥇', url: notoUrl('1f947') },
      { id: 'silvermedal1', name: 'Silver Medal 🥈', url: notoUrl('1f948') },
      { id: 'disco', name: 'Mirror Ball 🪩', url: notoUrl('1faa9') },
    ],
  },
  {
    id: 'hearts',
    name: 'Hearts & Love',
    emoji: '❤️',
    stickers: [
      { id: 'redheart', name: 'Heart ❤️', url: notoUrl('2764_fe0f') },
      { id: 'sparklingheart', name: 'Sparkling Heart 💖', url: notoUrl('1f496') },
      { id: 'growingheart', name: 'Growing Heart 💗', url: notoUrl('1f497') },
      { id: 'beatingheart', name: 'Beating Heart 💓', url: notoUrl('1f493') },
      { id: 'twohearts', name: 'Two Hearts 💕', url: notoUrl('1f495') },
      { id: 'revolvinghearts', name: 'Revolving Hearts 💞', url: notoUrl('1f49e') },
      { id: 'brokenheart', name: 'Broken Heart 💔', url: notoUrl('1f494') },
      { id: 'orangeheart', name: 'Orange Heart 🧡', url: notoUrl('1f9e1') },
      { id: 'yellowheart', name: 'Yellow Heart 💛', url: notoUrl('1f49b') },
      { id: 'blueheart', name: 'Blue Heart 💙', url: notoUrl('1f499') },
      { id: 'greenheart', name: 'Green Heart 💚', url: notoUrl('1f49a') },
      { id: 'purpleheart', name: 'Purple Heart 💜', url: notoUrl('1f49c') },
      { id: 'whiteheart', name: 'White Heart 🤍', url: notoUrl('1f90d') },
      { id: 'heartwithribbon', name: 'Gift Heart 💝', url: notoUrl('1f49d') },
      { id: 'hearthands', name: 'Love 🫶', url: notoUrl('1faf6') },
      { id: 'blackheart', name: 'Black Heart 🖤', url: notoUrl('1f5a4') },
      { id: 'brownheart', name: 'Brown Heart 🤎', url: notoUrl('1f90e') },
      { id: 'heartexclamation', name: 'Heart Exclamation ❣️', url: notoUrl('2763_fe0f') },
      { id: 'kissingheart', name: 'Kissing Heart 😘', url: notoUrl('1f618') },
      { id: 'hearteyes', name: 'Heart Eyes 😍', url: notoUrl('1f60d') },
      { id: 'lovehearts', name: 'Love Hearts 🥰', url: notoUrl('1f970') },
      { id: 'heartdecoration', name: 'Heart Decoration 💟', url: notoUrl('1f49f') },
      { id: 'heartarrow', name: 'Heart Arrow 💘', url: notoUrl('1f498') },
      { id: 'loveletter', name: 'Love Letter 💌', url: notoUrl('1f48c') },
      { id: 'hugheart', name: 'Hug 🤗', url: notoUrl('1f917') },
      { id: 'tulipheart', name: 'Tulip 🌷', url: notoUrl('1f337') },
      { id: 'fireheart', name: 'Heart on Fire ❤️‍🔥', url: notoUrl('2764_fe0f_200d_1f525') },
      { id: 'heartsuit', name: 'Heart Suit ♥️', url: notoUrl('2665_fe0f') },
      { id: 'kissmark', name: 'Kiss Mark 💋', url: notoUrl('1f48b') },
      { id: 'bouquet', name: 'Bouquet 💐', url: notoUrl('1f490') },
      { id: 'rose', name: 'Rose 🌹', url: notoUrl('1f339') },
      { id: 'catheart', name: 'Heart-Eyes Cat 😻', url: notoUrl('1f63b') },
      { id: 'huggingpeople', name: 'Together 🫂', url: notoUrl('1fac2') },
      { id: 'ring', name: 'Ring 💍', url: notoUrl('1f48d') },
      { id: 'homefamily', name: 'Home & Family 🏠', url: notoUrl('1f3e0') },
      { id: 'pinkheart', name: 'Pink Heart 🩷', url: notoUrl('1fa77') },
    ],
  },
  {
    id: 'smileys',
    name: 'Smileys',
    emoji: '😀',
    stickers: [
      { id: 'grin', name: 'Grin 😀', url: notoUrl('1f600') },
      { id: 'joy', name: 'Joy 😂', url: notoUrl('1f602') },
      { id: 'rofl', name: 'ROFL 🤣', url: notoUrl('1f923') },
      { id: 'smile', name: 'Smile 😊', url: notoUrl('1f60a') },
      { id: 'lovehearts', name: 'Hearts 🥰', url: notoUrl('1f970') },
      { id: 'hearteyes', name: 'Adore 😍', url: notoUrl('1f60d') },
      { id: 'kiss', name: 'Kiss 😘', url: notoUrl('1f618') },
      { id: 'tonguewink', name: 'Wink 😜', url: notoUrl('1f61c') },
      { id: 'cool', name: 'Cool 😎', url: notoUrl('1f60e') },
      { id: 'party', name: 'Party 🥳', url: notoUrl('1f973') },
      { id: 'thinking', name: 'Think 🤔', url: notoUrl('1f914') },
      { id: 'shush', name: 'Shh 🤫', url: notoUrl('1f92b') },
      { id: 'explode', name: 'Boom 🤯', url: notoUrl('1f92f') },
      { id: 'scream', name: 'Shock 😱', url: notoUrl('1f631') },
      { id: 'loudlycry', name: 'Sob 😭', url: notoUrl('1f62d') },
      { id: 'pleading', name: 'Please 🥺', url: notoUrl('1f97a') },
      { id: 'angry', name: 'Angry 😡', url: notoUrl('1f621') },
      { id: 'sleepy', name: 'Zzz 😴', url: notoUrl('1f634') },
      { id: 'unamused', name: 'Meh 😒', url: notoUrl('1f612') },
      { id: 'angel', name: 'Halo 😇', url: notoUrl('1f607') },
      { id: 'giggle', name: 'Oops 🤭', url: notoUrl('1f92d') },
      { id: 'nerd', name: 'Nerd 🤓', url: notoUrl('1f913') },
      { id: 'woozy', name: 'Woozy 🥴', url: notoUrl('1f974') },
      { id: 'sweatgrin', name: 'Sweat Grin 😅', url: notoUrl('1f605') },
      { id: 'tongue', name: 'Tongue 😛', url: notoUrl('1f61b') },
      { id: 'mask', name: 'Mask 😷', url: notoUrl('1f637') },
      { id: 'dizzy', name: 'Dizzy 😵', url: notoUrl('1f635') },
      { id: 'smirk', name: 'Smirk 😏', url: notoUrl('1f60f') },
      { id: 'winksmiley', name: 'Wink 😉', url: notoUrl('1f609') },
      { id: 'starstruck', name: 'Star-Struck 🤩', url: notoUrl('1f929') },
      { id: 'zanysmiley', name: 'Zany 🤪', url: notoUrl('1f92a') },
      { id: 'yawning', name: 'Yawn 🥱', url: notoUrl('1f971') },
      { id: 'upsidedown', name: 'Upside-Down Face 🙃', url: notoUrl('1f643') },
      { id: 'confused', name: 'Confused Face 😕', url: notoUrl('1f615') },
      { id: 'worried', name: 'Worried Face 😟', url: notoUrl('1f61f') },
      { id: 'salute', name: 'Salute 🫡', url: notoUrl('1fae1') },
    ],
  },
  {
    id: 'people',
    name: 'People & Gestures',
    emoji: '👋',
    stickers: [
      { id: 'wave', name: 'Hi 👋', url: notoUrl('1f44b') },
      { id: 'thumbsup', name: 'Like 👍', url: notoUrl('1f44d') },
      { id: 'thumbsdown', name: 'Dislike 👎', url: notoUrl('1f44e') },
      { id: 'clap', name: 'Clap 👏', url: notoUrl('1f44f') },
      { id: 'raisinghands', name: 'Yay 🙌', url: notoUrl('1f64c') },
      { id: 'pray', name: 'Pray 🙏', url: notoUrl('1f64f') },
      { id: 'handshake', name: 'Shake 🤝', url: notoUrl('1f91d') },
      { id: 'biceps', name: 'Flex 💪', url: notoUrl('1f4aa') },
      { id: 'hearthands', name: 'Love 🫶', url: notoUrl('1faf6') },
      { id: 'ok', name: 'OK 👌', url: notoUrl('1f44c') },
      { id: 'peace', name: 'Peace ✌️', url: notoUrl('270c_fe0f') },
      { id: 'rock', name: 'Rock 🤟', url: notoUrl('1f91f') },
      { id: 'horns', name: 'Horns 🤘', url: notoUrl('1f918') },
      { id: 'fist', name: 'Fist 👊', url: notoUrl('1f44a') },
      { id: 'fistright', name: 'Fist Bump 🤜', url: notoUrl('1f91c') },
      { id: 'fistleft', name: 'Fist Left 🤛', url: notoUrl('1f91b') },
      { id: 'raisedbackhand', name: 'Raised Back of Hand 🤚', url: notoUrl('1f91a') },
      { id: 'handsplayed', name: 'Hand 🖐️', url: notoUrl('1f590_fe0f') },
      { id: 'vulcan', name: 'Salute 🖖', url: notoUrl('1f596') },
      { id: 'pointleft', name: 'Point Left 👈', url: notoUrl('1f448') },
      { id: 'pointright', name: 'Point Right 👉', url: notoUrl('1f449') },
      { id: 'pointup', name: 'Point Up 👆', url: notoUrl('261d_fe0f') },
      { id: 'pointdown', name: 'Point Down 👇', url: notoUrl('1f447') },
      { id: 'callme', name: 'Call Me 🤙', url: notoUrl('1f919') },
      { id: 'crossedfingers', name: 'Luck 🤞', url: notoUrl('1f91e') },
      { id: 'nose', name: 'Nose 👃', url: notoUrl('1f443') },
      { id: 'nails', name: 'Nails 💅', url: notoUrl('1f485') },
      { id: 'eyes', name: 'Eyes 👀', url: notoUrl('1f440') },
      { id: 'ear', name: 'Ear 👂', url: notoUrl('1f442') },
      { id: 'brain', name: 'Brain 🧠', url: notoUrl('1f9e0') },
      { id: 'kissmark', name: 'Kiss 💋', url: notoUrl('1f48b') },
      { id: 'foot', name: 'Foot 🦶', url: notoUrl('1f9b6') },
      { id: 'leg', name: 'Leg 🦵', url: notoUrl('1f9b5') },
      { id: 'pinchedfingers', name: 'Pinched 🤌', url: notoUrl('1f90c') },
      { id: 'pinchinghand', name: 'Pinch 🤏', url: notoUrl('1f90f') },
      { id: 'indexpoint', name: 'Index Point 🫵', url: notoUrl('1faf5') },
    ],
  },
  {
    id: 'animals',
    name: 'Animals & Nature',
    emoji: '🐶',
    stickers: [
      { id: 'dog', name: 'Dog 🐕', url: notoUrl('1f415') },
      { id: 'cat', name: 'Cat 🐱', url: notoUrl('1f431') },
      { id: 'monkey', name: 'Monkey 🐒', url: notoUrl('1f412') },
      { id: 'lion', name: 'Lion 🦁', url: notoUrl('1f981') },
      { id: 'goat', name: 'Goat 🐐', url: notoUrl('1f410') },
      { id: 'chipmunk', name: 'Chipmunk 🐿️', url: notoUrl('1f43f_fe0f') },
      { id: 'unicorn', name: 'Unicorn 🦄', url: notoUrl('1f984') },
      { id: 'bee', name: 'Bee 🐝', url: notoUrl('1f41d') },
      { id: 'owl', name: 'Owl 🦉', url: notoUrl('1f989') },
      { id: 'pigeon', name: 'Dove of Peace 🕊️', url: notoUrl('1f54a_fe0f') },
      { id: 'bird', name: 'Bird 🐦', url: notoUrl('1f426') },
      { id: 'rose', name: 'Rose 🌹', url: notoUrl('1f339') },
      { id: 'panda', name: 'Panda 🐼', url: notoUrl('1f43c') },
      { id: 'rabbit', name: 'Rabbit 🐇', url: notoUrl('1f407') },
      { id: 'bouquet', name: 'Bouquet 💐', url: notoUrl('1f490') },
      { id: 'fox', name: 'Fox 🦊', url: notoUrl('1f98a') },
      { id: 'seemonkey', name: 'See-No-Evil Monkey 🙈', url: notoUrl('1f648') },
      { id: 'horse', name: 'Horse 🐎', url: notoUrl('1f40e') },
      { id: 'cow', name: 'Cow 🐮', url: notoUrl('1f42e') },
      { id: 'rooster', name: 'Rooster 🐓', url: notoUrl('1f413') },
      { id: 'penguin', name: 'Penguin 🐧', url: notoUrl('1f427') },
      { id: 'tulip', name: 'Tulip 🌷', url: notoUrl('1f337') },
      { id: 'eagle', name: 'Eagle 🦅', url: notoUrl('1f985') },
      { id: 'butterfly', name: 'Butterfly 🦋', url: notoUrl('1f98b') },
      { id: 'flower', name: 'Flower 🌸', url: notoUrl('1f338') },
      { id: 'blossom', name: 'Blossom 🌼', url: notoUrl('1f33c') },
      { id: 'leaf', name: 'Leaf 🍃', url: notoUrl('1f343') },
      { id: 'cactus', name: 'Cactus 🌵', url: notoUrl('1f335') },
      { id: 'clover', name: 'Clover 🍀', url: notoUrl('1f340') },
      { id: 'mapleleaf', name: 'Maple Leaf 🍁', url: notoUrl('1f341') },
      { id: 'turtle', name: 'Turtle 🐢', url: notoUrl('1f422') },
      { id: 'bat', name: 'Bat 🦇', url: notoUrl('1f987') },
      { id: 'snake', name: 'Snake 🐍', url: notoUrl('1f40d') },
      { id: 'dragon', name: 'Dragon 🐉', url: notoUrl('1f409') },
      { id: 'wolf', name: 'Wolf 🐺', url: notoUrl('1f43a') },
      { id: 'sloth', name: 'Sloth 🦥', url: notoUrl('1f9a5') },
    ],
  },
  {
    id: 'food',
    name: 'Food & Drink',
    emoji: '🍔',
    stickers: [
      { id: 'burger', name: 'Burger 🍔', url: notoUrl('1f354') },
      { id: 'pizza', name: 'Pizza 🍕', url: notoUrl('1f355') },
      { id: 'bread', name: 'Bread 🍞', url: notoUrl('1f35e') },
      { id: 'popcorn', name: 'Popcorn 🍿', url: notoUrl('1f37f') },
      { id: 'donut', name: 'Donut 🍩', url: notoUrl('1f369') },
      { id: 'cake', name: 'Cake 🎂', url: notoUrl('1f382') },
      { id: 'icecream', name: 'Ice Cream 🍦', url: notoUrl('1f366') },
      { id: 'coffee', name: 'Coffee ☕', url: notoUrl('2615') },
      { id: 'boba', name: 'Boba 🧋', url: notoUrl('1f9cb') },
      { id: 'beer', name: 'Cheers 🍻', url: notoUrl('1f37b') },
      { id: 'taco', name: 'Taco 🌮', url: notoUrl('1f32e') },
      { id: 'burrito', name: 'Burrito 🌯', url: notoUrl('1f32f') },
      { id: 'hotdog', name: 'Hotdog 🌭', url: notoUrl('1f32d') },
      { id: 'ramen', name: 'Ramen 🍜', url: notoUrl('1f35c') },
      { id: 'oden', name: 'Oden 🍢', url: notoUrl('1f362') },
      { id: 'spaghetti', name: 'Spaghetti 🍝', url: notoUrl('1f35d') },
      { id: 'cookie', name: 'Cookie 🍪', url: notoUrl('1f36a') },
      { id: 'pear', name: 'Pear 🍐', url: notoUrl('1f350') },
      { id: 'cherries', name: 'Cherries 🍒', url: notoUrl('1f352') },
      { id: 'apple', name: 'Apple 🍎', url: notoUrl('1f34e') },
      { id: 'grapes', name: 'Grapes 🍇', url: notoUrl('1f347') },
      { id: 'strawberry', name: 'Strawberry 🍓', url: notoUrl('1f353') },
      { id: 'watermelon', name: 'Watermelon 🍉', url: notoUrl('1f349') },
      { id: 'avocado', name: 'Avocado 🥑', url: notoUrl('1f951') },
      { id: 'cocktail', name: 'Tropical 🍹', url: notoUrl('1f379') },
      { id: 'wine', name: 'Wine 🍷', url: notoUrl('1f377') },
      { id: 'juice', name: 'Juice 🧃', url: notoUrl('1f9c3') },
      { id: 'tea', name: 'Tea 🍵', url: notoUrl('1f375') },
      { id: 'pineapple', name: 'Pineapple 🍍', url: notoUrl('1f34d') },
      { id: 'poultryleg', name: 'Chicken Leg 🍗', url: notoUrl('1f357') },
      { id: 'babybottle', name: 'Baby Bottle 🍼', url: notoUrl('1f37c') },
      { id: 'corn', name: 'Corn 🌽', url: notoUrl('1f33d') },
      { id: 'broccoli', name: 'Broccoli 🥦', url: notoUrl('1f966') },
      { id: 'pretzel', name: 'Pretzel 🥨', url: notoUrl('1f968') },
      { id: 'tomato', name: 'Tomato 🍅', url: notoUrl('1f345') },
      { id: 'cupcake', name: 'Cupcake 🧁', url: notoUrl('1f9c1') },
    ],
  },
  {
    id: 'activities',
    name: 'Activities & Sports',
    emoji: '⚽',
    stickers: [
      { id: 'soccer', name: 'Soccer ⚽', url: notoUrl('26bd') },
      { id: 'trumpet', name: 'Trumpet 🎺', url: notoUrl('1f3ba') },
      { id: 'clapper', name: 'Movie 🎬', url: notoUrl('1f3ac') },
      { id: 'trophy', name: 'Trophy 🏆', url: notoUrl('1f3c6') },
      { id: 'target', name: 'Target 🎯', url: notoUrl('1f3af') },
      { id: 'goldmedal', name: 'Gold Medal 🥇', url: notoUrl('1f947') },
      { id: 'raceflag', name: 'Race Flag 🏁', url: notoUrl('1f3c1') },
      { id: 'tennis', name: 'Tennis 🎾', url: notoUrl('1f3be') },
      { id: 'theatermasks', name: 'Show 🎭', url: notoUrl('1f3ad') },
      { id: 'bowling', name: 'Bowling 🎳', url: notoUrl('1f3b3') },
      { id: 'ferris', name: 'Ferris Wheel 🎡', url: notoUrl('1f3a1') },
      { id: 'dancing', name: 'Dancing 💃', url: notoUrl('1f483') },
      { id: 'skateboarding', name: 'Skateboarding 🛹', url: notoUrl('1f6f9') },
      { id: 'silvermedal', name: 'Silver Medal 🥈', url: notoUrl('1f948') },
      { id: 'sparklesact', name: 'Sparkles ✨', url: notoUrl('2728') },
      { id: 'guitar', name: 'Guitar 🎸', url: notoUrl('1f3b8') },
      { id: 'violin', name: 'Violin 🎻', url: notoUrl('1f3bb') },
      { id: 'drums', name: 'Drums 🥁', url: notoUrl('1f941') },
      { id: 'saxophone', name: 'Saxophone 🎷', url: notoUrl('1f3b7') },
      { id: 'confettiball', name: 'Confetti 🎊', url: notoUrl('1f38a') },
      { id: 'star2', name: 'Star ⭐', url: notoUrl('2b50') },
      { id: 'crown', name: 'Crown 👑', url: notoUrl('1f451') },
      { id: 'boxer', name: 'Boxer 🥊', url: notoUrl('1f94b') },
      { id: 'magic', name: 'Magic 🪄', url: notoUrl('1fa84') },
      { id: 'basketball', name: 'Basketball 🏀', url: notoUrl('1f3c0') },
      { id: 'fishingrod', name: 'Fishing 🎣', url: notoUrl('1f3a3') },
      { id: 'rugbyball', name: 'Rugby 🏉', url: notoUrl('1f3c9') },
      { id: 'frisbee', name: 'Frisbee 🥏', url: notoUrl('1f94f') },
      { id: 'bronzemedal', name: 'Bronze Medal 🥉', url: notoUrl('1f949') },
      { id: 'gamedie', name: 'Game Die 🎲', url: notoUrl('1f3b2') },
      { id: 'eightball', name: '8-Ball 🎱', url: notoUrl('1f3b1') },
      { id: 'slots', name: 'Slots 🎰', url: notoUrl('1f3b0') },
      { id: 'coaster', name: 'Coaster 🎢', url: notoUrl('1f3a2') },
      { id: 'carousel', name: 'Carousel 🎠', url: notoUrl('1f3a0') },
      { id: 'gameplay', name: 'Target 🎯', url: notoUrl('1f3af') },
      { id: 'joystick', name: 'Video Game 🎮', url: notoUrl('1f3ae') },
    ],
  },
  {
    id: 'objects',
    name: 'Objects & Symbols',
    emoji: '💡',
    stickers: [
      { id: 'bulb', name: 'Idea 💡', url: notoUrl('1f4a1') },
      { id: 'rocket', name: 'Rocket 🚀', url: notoUrl('1f680') },
      { id: 'bomb', name: 'Bomb 💣', url: notoUrl('1f4a3') },
      { id: 'popper', name: 'Popper 🎉', url: notoUrl('1f389') },
      { id: 'gift', name: 'Present 🎁', url: notoUrl('1f381') },
      { id: 'gem', name: 'Gem 💎', url: notoUrl('1f48e') },
      { id: 'musicnotes', name: 'Music 🎶', url: notoUrl('1f3b6') },
      { id: 'hundred', name: '100 💯', url: notoUrl('1f4af') },
      { id: 'bell', name: 'Bell 🔔', url: notoUrl('1f514') },
      { id: 'chart', name: 'Chart 📊', url: notoUrl('1f4ca') },
      { id: 'laptop', name: 'Laptop 💻', url: notoUrl('1f4bb') },
      { id: 'camera', name: 'Camera 📸', url: notoUrl('1f4f7') },
      { id: 'tv', name: 'TV 📺', url: notoUrl('1f4fa') },
      { id: 'coin', name: 'Coin 🪙', url: notoUrl('1fa99') },
      { id: 'lock', name: 'Lock 🔒', url: notoUrl('1f512') },
      { id: 'money', name: 'Money 💸', url: notoUrl('1f4b8') },
      { id: 'megaphone', name: 'Megaphone 📣', url: notoUrl('1f4e3') },
      { id: 'boom', name: 'Boom 💥', url: notoUrl('1f4a5') },
      { id: 'crystal', name: 'Crystal Ball 🔮', url: notoUrl('1f52e') },
      { id: 'clock', name: 'Clock ⏰', url: notoUrl('23f0') },
      { id: 'globe', name: 'Globe 🌍', url: notoUrl('1f30d') },
      { id: 'dizzystar', name: 'Dizzy 💫', url: notoUrl('1f4ab') },
      { id: 'star', name: 'Star ⭐', url: notoUrl('2b50') },
      { id: 'checkmark', name: 'Check ✅', url: notoUrl('2705') },
      { id: 'warning', name: 'Warning ⚠️', url: notoUrl('26a0_fe0f') },
      { id: 'sparklesobj', name: 'Sparkles ✨', url: notoUrl('2728') },
      { id: 'fireworksobj', name: 'Fireworks 🎆', url: notoUrl('1f386') },
      { id: 'magic', name: 'Magic 🪄', url: notoUrl('1fa84') },
      { id: 'rainbow2', name: 'Rainbow 🌈', url: notoUrl('1f308') },
      { id: 'fireobj', name: 'Fire 🔥', url: notoUrl('1f525') },
      { id: 'package2', name: 'Package 📦', url: notoUrl('1f4e6') },
      { id: 'balloonobj', name: 'Balloon 🎈', url: notoUrl('1f388') },
      { id: 'hourglass', name: 'Hourglass ⌛', url: notoUrl('231b') },
      { id: 'battery', name: 'Battery 🔋', url: notoUrl('1f50b') },
      { id: 'poop', name: 'Poop 💩', url: notoUrl('1f4a9') },
      { id: 'sparklingheartobj', name: 'Heart Sparkle 💖', url: notoUrl('1f496') },
    ],
  },
];