# Generated by Django 6.0.3 on 2026-04-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='ice_candidates',
            field=models.JSONField(blank=True, default=list, help_text='Buffered ICE candidates waiting for receiver', null=True),
        ),
    ]
