# Generated by Django 4.2.29 on 2026-03-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_delivered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
