# Generated by Django 4.2.29 on 2026-03-25 05:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_message_audio_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='cleared_by',
            field=models.ManyToManyField(blank=True, related_name='cleared_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
