# Generated by Django 6.0.3 on 2026-05-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_statuslike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='conversation_pics/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='media_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='chat_media/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='chat_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='status',
            name='media_file',
            field=models.FileField(max_length=255, upload_to='status_media/'),
        ),
    ]
