# Generated by Django 6.0.3 on 2026-05-15 07:29

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_alter_message_media_file_alter_status_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=500, null=True, storage=chat.models.get_image_storage, upload_to='conversation_pics/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='media_file',
            field=models.FileField(blank=True, max_length=500, null=True, storage=chat.models.get_universal_storage, upload_to='chat_media/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=500, null=True, storage=chat.models.get_image_storage, upload_to='chat_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='status',
            name='media_file',
            field=models.FileField(max_length=500, storage=chat.models.get_universal_storage, upload_to='status_media/'),
        ),
    ]
