# Generated by Django 6.0.3 on 2026-05-15 13:05

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_alter_conversation_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=chat.models.get_universal_storage, upload_to='conversation_pics/'),
        ),
    ]
