# Generated by Django 6.0.3 on 2026-05-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_alter_conversation_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=255, null=True, storage='chat.models.UniversalCloudinaryStorage', upload_to='conversation_pics/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='media_file',
            field=models.FileField(blank=True, max_length=255, null=True, storage='chat.models.UniversalCloudinaryStorage', upload_to='chat_media/'),
        ),
        migrations.AlterField(
            model_name='status',
            name='media_file',
            field=models.FileField(max_length=255, storage='chat.models.UniversalCloudinaryStorage', upload_to='status_media/'),
        ),
    ]
