# Generated by Django 6.0.3 on 2026-05-25 11:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_alter_conversation_profile_picture_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='restricted_to',
            field=models.ManyToManyField(blank=True, related_name='visible_statuses', to=settings.AUTH_USER_MODEL),
        ),
    ]
