# Generated by Django 6.0.3 on 2026-05-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_statusprivacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='caption_rotation',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='status',
            name='caption_scale',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='status',
            name='caption_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='status',
            name='caption_y',
            field=models.FloatField(default=0.0),
        ),
    ]
