# Generated by Django 6.0.3 on 2026-07-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_messagerequest_friendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('system', 'System Notification'), ('lottie_sticker', 'Lottie Sticker')], default='text', max_length=20),
        ),
    ]
