# Generated by Django 6.0.3 on 2026-08-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0021_alter_message_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='media_group_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
