# Generated by Django 6.0.3 on 2026-06-16 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicWatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=255)),
                ('source', models.CharField(default='youtube', max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('thumbnail', models.CharField(blank=True, max_length=1000, null=True)),
                ('channel_title', models.CharField(blank=True, max_length=255, null=True)),
                ('watched_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Music watch histories',
                'ordering': ['-watched_at'],
            },
        ),
        migrations.CreateModel(
            name='MusicLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=255)),
                ('source', models.CharField(default='youtube', max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('thumbnail', models.CharField(blank=True, max_length=1000, null=True)),
                ('channel_title', models.CharField(blank=True, max_length=255, null=True)),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-liked_at'],
                'unique_together': {('user', 'video_id', 'source')},
            },
        ),
    ]
